openc command "D:\Projects_code\ball_plate\cfile\translate.cfile" nodialog
bgstyle plain
openc keyword "D:\Projects_code\ball_plate\output\ball_plate.k"
 Time to read keyword file =  0.047 seconds
 Time to process element data =  0.012 seconds
Finished reading model
genselect target node
genselect transfer 0
genselect node add part 2
translate_model -22.318128001352335 -69.73595214371373 16.79423227229405
save keywordabsolute 0
save keywordbylongfmt 0
save keywordbyi10fmt 0
save keyword "D:\Projects_code\ball_plate\output\20260122_083440\ball_plate_translate.k"
exit
Save Config. parameters to file C:\Users\hoanh\AppData\Roaming\LSTC\LS-PrePost4.11\lsppconf
